/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ModelRegistry } from "./ModelRegistry";
export * as factories from "./factories";
export { ModelRegistry__factory } from "./factories/ModelRegistry__factory";
