/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ModelRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchCount"
      | "getBatchForModel"
      | "getMerkleRoot"
      | "getModel"
      | "isRegistered"
      | "owner"
      | "registerMerkleRoot"
      | "registerModel"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MerkleRootRegistered" | "ModelRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchForModel",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleRoot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getModel", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMerkleRoot",
    values: [BytesLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerModel",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "batchCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBatchForModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getModel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerModel",
    data: BytesLike
  ): Result;
}

export namespace MerkleRootRegisteredEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    root: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [batchId: bigint, root: string, timestamp: bigint];
  export interface OutputObject {
    batchId: bigint;
    root: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModelRegisteredEvent {
  export type InputTuple = [
    modelId: string,
    hash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [modelId: string, hash: string, timestamp: bigint];
  export interface OutputObject {
    modelId: string;
    hash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ModelRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ModelRegistry;
  waitForDeployment(): Promise<this>;

  interface: ModelRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchCount: TypedContractMethod<[], [bigint], "view">;

  getBatchForModel: TypedContractMethod<[modelId: string], [bigint], "view">;

  getMerkleRoot: TypedContractMethod<
    [batchId: BigNumberish],
    [
      [string, bigint, string[]] & {
        root: string;
        timestamp: bigint;
        modelIds: string[];
      }
    ],
    "view"
  >;

  getModel: TypedContractMethod<
    [modelId: string],
    [[string, bigint] & { hash: string; timestamp: bigint }],
    "view"
  >;

  isRegistered: TypedContractMethod<[modelId: string], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerMerkleRoot: TypedContractMethod<
    [root: BytesLike, modelIds: string[]],
    [void],
    "nonpayable"
  >;

  registerModel: TypedContractMethod<
    [modelId: string, hash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBatchForModel"
  ): TypedContractMethod<[modelId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMerkleRoot"
  ): TypedContractMethod<
    [batchId: BigNumberish],
    [
      [string, bigint, string[]] & {
        root: string;
        timestamp: bigint;
        modelIds: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getModel"
  ): TypedContractMethod<
    [modelId: string],
    [[string, bigint] & { hash: string; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[modelId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerMerkleRoot"
  ): TypedContractMethod<
    [root: BytesLike, modelIds: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerModel"
  ): TypedContractMethod<
    [modelId: string, hash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MerkleRootRegistered"
  ): TypedContractEvent<
    MerkleRootRegisteredEvent.InputTuple,
    MerkleRootRegisteredEvent.OutputTuple,
    MerkleRootRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ModelRegistered"
  ): TypedContractEvent<
    ModelRegisteredEvent.InputTuple,
    ModelRegisteredEvent.OutputTuple,
    ModelRegisteredEvent.OutputObject
  >;

  filters: {
    "MerkleRootRegistered(uint256,bytes32,uint256)": TypedContractEvent<
      MerkleRootRegisteredEvent.InputTuple,
      MerkleRootRegisteredEvent.OutputTuple,
      MerkleRootRegisteredEvent.OutputObject
    >;
    MerkleRootRegistered: TypedContractEvent<
      MerkleRootRegisteredEvent.InputTuple,
      MerkleRootRegisteredEvent.OutputTuple,
      MerkleRootRegisteredEvent.OutputObject
    >;

    "ModelRegistered(string,bytes32,uint256)": TypedContractEvent<
      ModelRegisteredEvent.InputTuple,
      ModelRegisteredEvent.OutputTuple,
      ModelRegisteredEvent.OutputObject
    >;
    ModelRegistered: TypedContractEvent<
      ModelRegisteredEvent.InputTuple,
      ModelRegisteredEvent.OutputTuple,
      ModelRegisteredEvent.OutputObject
    >;
  };
}
